// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <imager.h>;
#include <Rcpp.h>
using namespace cimg_library;

using namespace Rcpp;

// C_solid_blobs
LogicalVector C_solid_blobs(NumericVector img_inp, IntegerMatrix stencil);
RcppExport SEXP ssoftveR_C_solid_blobs(SEXP img_inpSEXP, SEXP stencilSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type img_inp(img_inpSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type stencil(stencilSEXP);
    rcpp_result_gen = Rcpp::wrap(C_solid_blobs(img_inp, stencil));
    return rcpp_result_gen;
END_RCPP
}

