// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <imager.h>;
#include <Rcpp.h>
using namespace cimg_library;

using namespace Rcpp;

// C_solid_blobs
LogicalVector C_solid_blobs(NumericVector img_inp);
RcppExport SEXP ssoftveR_C_solid_blobs(SEXP img_inpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type img_inp(img_inpSEXP);
    rcpp_result_gen = Rcpp::wrap(C_solid_blobs(img_inp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"ssoftveR_C_solid_blobs", (DL_FUNC) &ssoftveR_C_solid_blobs, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ssoftveR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
