# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_solid_blobs <- function(img_inp) {
    .Call('ssoftveR_C_solid_blobs', PACKAGE = 'ssoftveR', img_inp)
}

